const STORE_BENEFICIARY = 'STORE_BENEFICIARY';
const RESET_ARAMCO_STATE = 'RESET_ARAMCO_STATE';
const STORE_ACCOUNT = 'STORE_ACCOUNT';
const STORE_BENEFICIARY_DETAILS = 'STORE_BENEFICIARY_DETAILS';

export { STORE_BENEFICIARY, RESET_ARAMCO_STATE, STORE_ACCOUNT, STORE_BENEFICIARY_DETAILS };
